#ifndef AP_CTPEVENTSTRUCT_H__
#define AP_CTPEVENTSTRUCT_H__

#include "ThostFtdcUserApiStruct.h"

#define EventCallbackStruct_11001 void
#define EventCallbackStruct_11002 void
#define EventCallbackStruct_11003 void
#define EventCallbackStruct_11004 CThostFtdcInstrumentStatusField
#define EventCallbackStruct_11005 CThostFtdcTradingNoticeInfoField
#define EventCallbackStruct_11006 CThostFtdcBulletinField
#define EventCallbackStruct_11007 CThostFtdcSpecificInstrumentField
#define EventCallbackStruct_11008 CThostFtdcSpecificInstrumentField
#define EventCallbackStruct_11009 CThostFtdcUserPasswordUpdateField
#define EventCallbackStruct_11010 CThostFtdcTradingAccountPasswordUpdateField
#define EventCallbackStruct_11011 CThostFtdcRspTransferField

#define EventCallbackStruct_11101 CThostFtdcRspUserLoginField
#define EventCallbackStruct_11102 CThostFtdcRspUserLoginField
#define EventCallbackStruct_11103 CThostFtdcRspAuthenticateField
#define EventCallbackStruct_11104 CThostFtdcSettlementInfoConfirmField

#define EventCallbackStruct_11201 CThostFtdcSettlementInfoField
#define EventCallbackStruct_11202 CThostFtdcOrderField
#define EventCallbackStruct_11203 CThostFtdcInstrumentOrderCommRateField
#define EventCallbackStruct_11204 CThostFtdcTradeField
#define EventCallbackStruct_11205 CThostFtdcInvestorPositionField
#define EventCallbackStruct_11206 CThostFtdcInvestorPositionDetailField
#define EventCallbackStruct_11207 CThostFtdcTradingAccountField
#define EventCallbackStruct_11208 CThostFtdcNotifyQueryAccountField
#define EventCallbackStruct_11209 CThostFtdcTransferSerialField

#define EventCallbackStruct_11210 CThostFtdcExecOrderField
#define EventCallbackStruct_11211 CThostFtdcForQuoteField
#define EventCallbackStruct_11212 CThostFtdcQuoteField
#define EventCallbackStruct_11213 CThostFtdcOptionSelfCloseField
#define EventCallbackStruct_11214 CThostFtdcParkedOrderField
#define EventCallbackStruct_11215 CThostFtdcParkedOrderActionField
#define EventCallbackStruct_11216 CThostFtdcCombActionField
#define EventCallbackStruct_11217 CThostFtdcInvestorPositionCombineDetailField

#define EventCallbackStruct_11301 CThostFtdcInvestorField
#define EventCallbackStruct_11302 CThostFtdcTradingCodeField
#define EventCallbackStruct_11303 CThostFtdcCFMMCTradingAccountKeyField
#define EventCallbackStruct_11304 CThostFtdcCFMMCTradingAccountTokenField
#define EventCallbackStruct_11305 CThostFtdcAccountregisterField
#define EventCallbackStruct_11306 CThostFtdcContractBankField
#define EventCallbackStruct_11307 CThostFtdcQryMaxOrderVolumeField
#define EventCallbackStruct_11308 CThostFtdcTransferBankField
#define EventCallbackStruct_11309 CThostFtdcOptionInstrTradeCostField
#define EventCallbackStruct_11310 CThostFtdcInstrumentMarginRateField
#define EventCallbackStruct_11311 CThostFtdcInvestorProductGroupMarginField
#define EventCallbackStruct_11312 CThostFtdcInstrumentCommissionRateField
#define EventCallbackStruct_11313 CThostFtdcOptionInstrCommRateField
#define EventCallbackStruct_11314 CThostFtdcMMInstrumentCommissionRateField
#define EventCallbackStruct_11315 CThostFtdcMMOptionInstrCommRateField
#define EventCallbackStruct_11316 CThostFtdcSettlementInfoConfirmField
#define EventCallbackStruct_11317 CThostFtdcTradingNoticeField

#define EventCallbackStruct_11318 CThostFtdcSecAgentACIDMapField
#define EventCallbackStruct_11319 CThostFtdcTradingAccountField
#define EventCallbackStruct_11320 CThostFtdcSecAgentCheckModeField
#define EventCallbackStruct_11321 CThostFtdcSecAgentTradeInfoField
#define EventCallbackStruct_11322 CThostFtdcBrokerTradingParamsField
#define EventCallbackStruct_11323 CThostFtdcBrokerTradingAlgosField

#define EventCallbackStruct_11401 CThostFtdcDepthMarketDataField
#define EventCallbackStruct_11402 CThostFtdcInstrumentField
#define EventCallbackStruct_11403 CThostFtdcCombInstrumentGuardField
#define EventCallbackStruct_11404 CThostFtdcProductField
#define EventCallbackStruct_11405 CThostFtdcProductGroupField
#define EventCallbackStruct_11406 CThostFtdcExchangeField
#define EventCallbackStruct_11407 CThostFtdcExchangeMarginRateField
#define EventCallbackStruct_11408 CThostFtdcExchangeMarginRateAdjustField
#define EventCallbackStruct_11409 CThostFtdcNoticeField
#define EventCallbackStruct_11410 CThostFtdcEWarrantOffsetField
#define EventCallbackStruct_11411 CThostFtdcExchangeRateField
#define EventCallbackStruct_11412 CThostFtdcProductExchRateField

#endif
